#!/usr/bin/env bash
# ============================================================
# Script: generate-inventory.sh
# Purpose: Generate code inventory (models, services, routes) in markdown
# Usage: ./scripts/maintenance/generate-inventory.sh [--models|--services|--routes|--check|--all]
# Dependencies: jq
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/docs/inventory"
MODE="${1:---all}"
CHECK_ONLY=false

if [ "$MODE" = "--check" ]; then
  CHECK_ONLY=true
  MODE="--all"
fi

mkdir -p "$OUTPUT_DIR"

# ============================================================
# Models/Entities Inventory
# Tracks: Agent definitions, configuration schemas, data models
# ============================================================
generate_models_inventory() {
  echo "Generating models inventory..." >&2

  cat <<'HEADER'
# Models & Entities Inventory

Auto-generated inventory of all models, entities, and data definitions in the repository.

> Generated by `scripts/maintenance/generate-inventory.sh`

## Agent Definitions

| Model | Location | Purpose | Dependencies |
|-------|----------|---------|--------------|
HEADER

  # Core agents
  local agent_dirs=()
  for d in core/agents domains/*/agents packs/*/agents; do
    [ -d "$d" ] && agent_dirs+=("$d")
  done

  if [ ${#agent_dirs[@]} -gt 0 ]; then
    while IFS= read -r agent; do
      [ -f "$agent" ] || continue
      local name purpose deps
      name=$(basename "$agent" .md)
      purpose=$(grep -m1 "^description:" "$agent" 2>/dev/null | sed 's/^description: *//' | cut -c1-60 || echo "Agent definition")
      deps=$(grep -m1 "^model:" "$agent" 2>/dev/null | sed 's/^model: *//' || echo "-")
      echo "| $name | \`$agent\` | $purpose | model: $deps |"
    done < <(find "${agent_dirs[@]}" -name "*.md" -type f 2>/dev/null | sort)
  fi

  cat <<'HEADER'

## Configuration Schemas

| Model | Location | Purpose | Dependencies |
|-------|----------|---------|--------------|
HEADER

  # Config files (YAML/JSON that define schemas)
  local config_dirs=()
  for d in core/config config; do
    [ -d "$d" ] && config_dirs+=("$d")
  done

  if [ ${#config_dirs[@]} -gt 0 ]; then
    while IFS= read -r config; do
      [ -f "$config" ] || continue
      local name purpose
      name=$(basename "$config")
      purpose=$(head -3 "$config" | grep -i "^#" | sed 's/^#* *//' | head -1 || echo "Configuration")
      [ -z "$purpose" ] && purpose="Configuration schema"
      echo "| $name | \`$config\` | $purpose | - |"
    done < <(find "${config_dirs[@]}" \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) 2>/dev/null | sort)
  fi

  cat <<'HEADER'

## Data Scripts (State Generators)

| Model | Location | Purpose | Dependencies |
|-------|----------|---------|--------------|
HEADER

  # Data scripts that produce structured state
  while IFS= read -r script; do
    [ -f "$script" ] || continue
    local name purpose deps
    name=$(basename "$script" .sh)
    purpose=$(grep "^# Purpose:" "$script" 2>/dev/null | cut -d: -f2- | xargs || echo "Data generation")
    deps=$(grep "^# Dependencies:" "$script" 2>/dev/null | cut -d: -f2- | xargs || echo "-")
    echo "| $name | \`$script\` | $purpose | $deps |"
  done < <(find scripts -name "*-data.sh" -type f 2>/dev/null | sort)

  # Summary
  local agent_count config_count data_count
  if [ ${#agent_dirs[@]} -gt 0 ]; then
    agent_count=$(find "${agent_dirs[@]}" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  else
    agent_count=0
  fi
  local config_dirs=()
  for d in core/config config; do
    [ -d "$d" ] && config_dirs+=("$d")
  done
  if [ ${#config_dirs[@]} -gt 0 ]; then
    config_count=$(find "${config_dirs[@]}" \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) 2>/dev/null | wc -l | tr -d ' ')
  else
    config_count=0
  fi
  data_count=$(find scripts -name "*-data.sh" -type f 2>/dev/null | wc -l | tr -d ' ')

  cat <<EOF

---

## Summary

| Category | Count |
|----------|-------|
| Agent Definitions | $agent_count |
| Configuration Schemas | $config_count |
| Data Scripts | $data_count |
| **Total** | **$((agent_count + config_count + data_count))** |

*Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF
}

# ============================================================
# Services Inventory
# Tracks: Shell scripts providing operational services
# ============================================================
generate_services_inventory() {
  echo "Generating services inventory..." >&2

  cat <<'HEADER'
# Services Inventory

Auto-generated inventory of all services (operational scripts) in the repository.

> Generated by `scripts/maintenance/generate-inventory.sh`

## Script Services

| Service | Location | Responsibility | Dependencies |
|---------|----------|----------------|--------------|
HEADER

  while IFS= read -r script; do
    [ -f "$script" ] || continue
    local name purpose deps category
    name=$(basename "$script" .sh)
    purpose=$(grep "^# Purpose:" "$script" 2>/dev/null | cut -d: -f2- | xargs || echo "")
    [ -z "$purpose" ] && purpose=$(grep "^# Script:" "$script" -A2 2>/dev/null | grep "^# " | tail -1 | sed 's/^# *//' || echo "Operational script")
    deps=$(grep "^# Dependencies:" "$script" 2>/dev/null | cut -d: -f2- | xargs || echo "-")

    echo "| $name | \`$script\` | $purpose | $deps |"
  done < <(find scripts -name "*.sh" -type f -not -path "*/lib/*" 2>/dev/null | sort)

  cat <<'HEADER'

## Shared Libraries

| Service | Location | Responsibility | Dependencies |
|---------|----------|----------------|--------------|
HEADER

  while IFS= read -r lib; do
    [ -f "$lib" ] || continue
    local name purpose
    name=$(basename "$lib" .sh)
    purpose=$(grep "^# Purpose:" "$lib" 2>/dev/null | cut -d: -f2- | xargs || echo "Shared utilities")
    echo "| $name | \`$lib\` | $purpose | - |"
  done < <(find scripts/lib -name "*.sh" -type f 2>/dev/null | sort)

  # Summary by category
  cat <<'HEADER'

## Services by Category

| Category | Count | Total Lines |
|----------|-------|-------------|
HEADER

  for category in audit ci dev hooks maintenance lib; do
    local count lines
    count=$(find "scripts/$category" -name "*.sh" -type f 2>/dev/null | wc -l | tr -d ' ')
    if [ "$count" -gt 0 ]; then
      lines=$(find "scripts/$category" -name "*.sh" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
      echo "| $category | $count | $lines |"
    fi
  done

  local root_count root_lines
  root_count=$(find scripts -maxdepth 1 -name "*.sh" -type f 2>/dev/null | wc -l | tr -d ' ')
  root_lines=$(find scripts -maxdepth 1 -name "*.sh" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
  echo "| root | $root_count | $root_lines |"

  local total_count total_lines
  total_count=$(find scripts -name "*.sh" -type f 2>/dev/null | wc -l | tr -d ' ')
  total_lines=$(find scripts -name "*.sh" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
  echo "| **Total** | **$total_count** | **$total_lines** |"

  echo ""
  echo "*Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*"
}

# ============================================================
# Routes Inventory
# Tracks: Commands (slash commands), workflows, entry points
# ============================================================
generate_routes_inventory() {
  echo "Generating routes inventory..." >&2

  cat <<'HEADER'
# Routes & Commands Inventory

Auto-generated inventory of all commands (entry points) and workflows in the repository.

> Generated by `scripts/maintenance/generate-inventory.sh`

## Slash Commands

| Route | Method | Handler | Auth Required |
|-------|--------|---------|---------------|
HEADER

  local cmd_dirs=()
  for d in core/commands packs/*/commands domains/*/commands; do
    [ -d "$d" ] && cmd_dirs+=("$d")
  done

  if [ ${#cmd_dirs[@]} -gt 0 ]; then
    while IFS= read -r cmd; do
      [ -f "$cmd" ] || continue
      local name handler
      name=$(basename "$cmd" .md)
      handler="$cmd"
      echo "| /$name | invoke | \`$handler\` | No |"
    done < <(find "${cmd_dirs[@]}" -name "*.md" -type f 2>/dev/null | sort)
  fi

  cat <<'HEADER'

## GitHub Actions Workflows

| Route | Method | Handler | Auth Required |
|-------|--------|---------|---------------|
HEADER

  while IFS= read -r workflow; do
    [ -f "$workflow" ] || continue
    local name trigger
    name=$(basename "$workflow" .yml)
    trigger=$(grep -E "^\s+(push|pull_request|schedule|workflow_dispatch):" "$workflow" 2>/dev/null | head -1 | xargs || echo "manual")
    echo "| .github/workflows/$name | $trigger | \`$workflow\` | Yes (GITHUB_TOKEN) |"
  done < <(find .github/workflows -name "*.yml" -o -name "*.yaml" 2>/dev/null | sort)

  cat <<'HEADER'

## Skills (Reusable Procedures)

| Route | Method | Handler | Auth Required |
|-------|--------|---------|---------------|
HEADER

  local skill_dirs=()
  for d in core/skills packs/*/skills domains/*/skills; do
    [ -d "$d" ] && skill_dirs+=("$d")
  done

  if [ ${#skill_dirs[@]} -gt 0 ]; then
    while IFS= read -r skill; do
      [ -f "$skill" ] || continue
      local name
      name=$(basename "$skill" .md)
      echo "| /skill:$name | invoke | \`$skill\` | No |"
    done < <(find "${skill_dirs[@]}" -name "*.md" -type f 2>/dev/null | sort)
  fi

  # Summary
  local cmd_count wf_count skill_count
  if [ ${#cmd_dirs[@]} -gt 0 ]; then
    cmd_count=$(find "${cmd_dirs[@]}" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  else
    cmd_count=0
  fi
  wf_count=$(find .github/workflows \( -name "*.yml" -o -name "*.yaml" \) 2>/dev/null | wc -l | tr -d ' ')
  if [ ${#skill_dirs[@]} -gt 0 ]; then
    skill_count=$(find "${skill_dirs[@]}" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  else
    skill_count=0
  fi

  cat <<EOF

---

## Summary

| Category | Count |
|----------|-------|
| Slash Commands | $cmd_count |
| GitHub Workflows | $wf_count |
| Skills | $skill_count |
| **Total Entry Points** | **$((cmd_count + wf_count + skill_count))** |

*Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF
}

# ============================================================
# Check mode: verify inventory freshness
# ============================================================
check_freshness() {
  local stale=false

  for file in models.md services.md routes.md; do
    if [ ! -f "$OUTPUT_DIR/$file" ]; then
      echo "STALE: $OUTPUT_DIR/$file does not exist" >&2
      stale=true
    fi
  done

  if [ "$stale" = true ]; then
    echo "Inventory is stale. Run: ./scripts/maintenance/generate-inventory.sh" >&2
    exit 1
  fi

  # Generate fresh and compare
  local tmpdir
  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  generate_models_inventory > "$tmpdir/models.md" 2>/dev/null
  generate_services_inventory > "$tmpdir/services.md" 2>/dev/null
  generate_routes_inventory > "$tmpdir/routes.md" 2>/dev/null

  for file in models.md services.md routes.md; do
    # Strip timestamp lines for comparison
    local current_clean fresh_clean
    current_clean=$(grep -v "^\\*Last generated:" "$OUTPUT_DIR/$file" 2>/dev/null || echo "")
    fresh_clean=$(grep -v "^\\*Last generated:" "$tmpdir/$file" 2>/dev/null || echo "")

    if [ "$current_clean" != "$fresh_clean" ]; then
      echo "STALE: $OUTPUT_DIR/$file has changed" >&2
      diff <(echo "$current_clean") <(echo "$fresh_clean") >&2 || true
      stale=true
    fi
  done

  if [ "$stale" = true ]; then
    echo "Inventory is stale. Run: ./scripts/maintenance/generate-inventory.sh" >&2
    exit 1
  fi

  echo "Inventory is up to date." >&2
  exit 0
}

# ============================================================
# Main
# ============================================================
main() {
  cd "$REPO_ROOT"

  if [ "$CHECK_ONLY" = true ]; then
    check_freshness
    return
  fi

  case "$MODE" in
    --models)
      generate_models_inventory > "$OUTPUT_DIR/models.md"
      echo "Models inventory saved to $OUTPUT_DIR/models.md" >&2
      ;;
    --services)
      generate_services_inventory > "$OUTPUT_DIR/services.md"
      echo "Services inventory saved to $OUTPUT_DIR/services.md" >&2
      ;;
    --routes)
      generate_routes_inventory > "$OUTPUT_DIR/routes.md"
      echo "Routes inventory saved to $OUTPUT_DIR/routes.md" >&2
      ;;
    --all|*)
      generate_models_inventory > "$OUTPUT_DIR/models.md"
      generate_services_inventory > "$OUTPUT_DIR/services.md"
      generate_routes_inventory > "$OUTPUT_DIR/routes.md"
      echo "All inventories saved to $OUTPUT_DIR/" >&2
      echo "  - models.md (agents, configs, data scripts)" >&2
      echo "  - services.md (operational scripts)" >&2
      echo "  - routes.md (commands, workflows, skills)" >&2
      ;;
  esac
}

main
