#!/bin/bash
set -euo pipefail
# auto-promote-to-qa.sh
# Automatic dev→qa promotion on milestone completion
#
# Usage:
#   ./scripts/auto-promote-to-qa.sh                      # Auto-promote for active milestone
#   ./scripts/auto-promote-to-qa.sh "MVP"                # Auto-promote for specific milestone
#   ./scripts/auto-promote-to-qa.sh --milestone "MVP"    # Alternative syntax
#   ./scripts/auto-promote-to-qa.sh --dry-run            # Preview without action
#   ./scripts/auto-promote-to-qa.sh --wait               # Wait for CI after PR creation
#   ./scripts/auto-promote-to-qa.sh --no-merge           # Create PR but don't auto-merge
#
# Outputs JSON with:
#   - action: What was done (created_pr, merged_pr, skipped, error)
#   - pr: PR details if created/merged
#   - message: Human-readable summary
#   - notifications: Suggested notification messages

set -e

# Navigate to repo root
cd "$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo '{"action": "error", "message": "Not in a git repository"}'
  exit 1
}

SCRIPT_DIR="$(dirname "$0")"

# Source changelog cache utility
if [ -f "$SCRIPT_DIR/lib/changelog-cache.sh" ]; then
  source "$SCRIPT_DIR/lib/changelog-cache.sh"
fi

MILESTONE_NAME=""
DRY_RUN=false
WAIT_FOR_CI=false
NO_MERGE=false
TIMEOUT=300  # 5 minutes default wait

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --milestone)
      MILESTONE_NAME="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --wait)
      WAIT_FOR_CI=true
      shift
      ;;
    --no-merge)
      NO_MERGE=true
      shift
      ;;
    --timeout)
      TIMEOUT="$2"
      shift 2
      ;;
    -*)
      shift
      ;;
    *)
      MILESTONE_NAME="$1"
      shift
      ;;
  esac
done

# Get data from data script
SCRIPT_DIR="$(dirname "$0")"
DATA=$("$SCRIPT_DIR/auto-promote-to-qa-data.sh" --changelog ${MILESTONE_NAME:+"$MILESTONE_NAME"})

# Check for error
if echo "$DATA" | jq -e '.error' >/dev/null 2>&1; then
  echo "$DATA"
  exit 1
fi

# Extract key values
MILESTONE_TITLE=$(echo "$DATA" | jq -r '.milestone.title')
CAN_PROMOTE=$(echo "$DATA" | jq -r '.readiness.can_auto_promote')
BLOCK_REASONS=$(echo "$DATA" | jq -c '.readiness.block_reasons')
EXISTING_PR=$(echo "$DATA" | jq '.existing_pr')
COMMITS_AHEAD=$(echo "$DATA" | jq -r '.branch_state.commits_ahead')
ALL_COMPLETE=$(echo "$DATA" | jq -r '.milestone.issues.all_complete')

# Build changelog summary for PR body
build_pr_body() {
  local changelog=$1
  local milestone=$2

  local features=$(echo "$changelog" | jq -r '.features | if length > 0 then "### Features\n" + (. | map("- " + .) | join("\n")) else "" end')
  local fixes=$(echo "$changelog" | jq -r '.fixes | if length > 0 then "### Fixes\n" + (. | map("- " + .) | join("\n")) else "" end')
  local other=$(echo "$changelog" | jq -r '.other | if length > 0 then "### Other\n" + (. | map("- " + .) | join("\n")) else "" end')

  cat <<EOF
## QA Validation - Milestone: $milestone

This PR promotes \`dev\` to \`qa\` following milestone completion.

$features

$fixes

$other

---

### QA Checklist
- [ ] Functional testing complete
- [ ] Regression testing complete
- [ ] Performance acceptable
- [ ] No blocking issues found

### After QA Sign-off
Use \`/pr-to-main\` to promote qa to main for production release.

---
*Auto-generated by milestone completion workflow*
EOF
}

# Wait for CI checks to complete
wait_for_ci() {
  local pr_number=$1
  local timeout=$2
  local elapsed=0
  local interval=10

  while [ $elapsed -lt $timeout ]; do
    local status=$(gh pr checks "$pr_number" --json state --jq '.[] | select(.state != "SUCCESS" and .state != "FAILURE") | .state' 2>/dev/null | head -1)

    if [ -z "$status" ]; then
      # All checks complete - verify success
      local failed=$(gh pr checks "$pr_number" --json state --jq '.[] | select(.state == "FAILURE") | .state' 2>/dev/null | head -1)
      if [ -n "$failed" ]; then
        echo "failure"
        return 1
      fi
      echo "success"
      return 0
    fi

    sleep $interval
    elapsed=$((elapsed + interval))
  done

  echo "timeout"
  return 1
}

# Check if we can proceed
if [ "$CAN_PROMOTE" != "true" ]; then
  jq -n \
    --arg action "blocked" \
    --argjson reasons "$BLOCK_REASONS" \
    --arg milestone "$MILESTONE_TITLE" \
    '{
      action: $action,
      milestone: $milestone,
      message: "Cannot auto-promote: \($reasons | join(", "))",
      block_reasons: $reasons
    }'
  exit 0
fi

# Dry run mode
if [ "$DRY_RUN" = true ]; then
  CHANGELOG=$(echo "$DATA" | jq '.changelog')

  jq -n \
    --arg action "dry_run" \
    --arg milestone "$MILESTONE_TITLE" \
    --argjson commits "$COMMITS_AHEAD" \
    --argjson existing_pr "$EXISTING_PR" \
    --argjson changelog "$CHANGELOG" \
    '{
      action: $action,
      milestone: $milestone,
      would_do: {
        create_pr: ($existing_pr == null),
        commits_to_promote: $commits,
        auto_merge: true
      },
      existing_pr: $existing_pr,
      changelog: $changelog,
      message: "Dry run: Would promote \($commits) commits from dev to qa"
    }'
  exit 0
fi

# Handle existing PR
PR_NUMBER=""
PR_URL=""

if [ "$EXISTING_PR" != "null" ]; then
  PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number')
  PR_URL=$(echo "$EXISTING_PR" | jq -r '.url')
  echo "Found existing PR #$PR_NUMBER" >&2
else
  # Create new PR
  CHANGELOG=$(echo "$DATA" | jq '.changelog')
  PR_BODY=$(build_pr_body "$CHANGELOG" "$MILESTONE_TITLE")

  # Create the PR
  PR_RESULT=$(gh pr create \
    --base qa \
    --head dev \
    --title "qa: Promote dev for QA validation - $MILESTONE_TITLE" \
    --body "$PR_BODY" \
    2>&1) || {
    jq -n \
      --arg action "error" \
      --arg message "Failed to create PR: $PR_RESULT" \
      '{action: $action, message: $message}'
    exit 1
  }

  # Extract PR URL
  PR_URL="$PR_RESULT"
  PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

  echo "Created PR #$PR_NUMBER: $PR_URL" >&2

  # Cache the changelog and PR body for later use in qa→main promotion
  # This significantly reduces API calls during final release
  if type cache_promotion_metadata >/dev/null 2>&1 && [ "$CHANGELOG" != "null" ]; then
    cache_promotion_metadata "dev" "qa" "$PR_NUMBER" "$PR_BODY" "$CHANGELOG" 2>/dev/null || true
  fi
fi

# If --no-merge, stop here
if [ "$NO_MERGE" = true ]; then
  jq -n \
    --arg action "created_pr" \
    --arg milestone "$MILESTONE_TITLE" \
    --argjson pr_number "$PR_NUMBER" \
    --arg pr_url "$PR_URL" \
    --argjson commits "$COMMITS_AHEAD" \
    '{
      action: $action,
      milestone: $milestone,
      pr: {
        number: $pr_number,
        url: $pr_url
      },
      commits_promoted: $commits,
      message: "PR created. Auto-merge disabled.",
      next_steps: ["Review PR", "Merge manually when ready", "Run /pr-to-main after QA validation"]
    }'
  exit 0
fi

# Wait for CI if requested
if [ "$WAIT_FOR_CI" = true ]; then
  echo "Waiting for CI checks on PR #$PR_NUMBER..." >&2
  CI_RESULT=$(wait_for_ci "$PR_NUMBER" "$TIMEOUT")

  if [ "$CI_RESULT" = "failure" ]; then
    jq -n \
      --arg action "ci_failed" \
      --arg milestone "$MILESTONE_TITLE" \
      --argjson pr_number "$PR_NUMBER" \
      --arg pr_url "$PR_URL" \
      '{
        action: $action,
        milestone: $milestone,
        pr: {
          number: $pr_number,
          url: $pr_url
        },
        message: "CI checks failed. PR created but not merged.",
        next_steps: ["Fix CI failures", "Manually merge when ready"]
      }'
    exit 1
  fi

  if [ "$CI_RESULT" = "timeout" ]; then
    jq -n \
      --arg action "ci_timeout" \
      --arg milestone "$MILESTONE_TITLE" \
      --argjson pr_number "$PR_NUMBER" \
      --arg pr_url "$PR_URL" \
      --argjson timeout "$TIMEOUT" \
      '{
        action: $action,
        milestone: $milestone,
        pr: {
          number: $pr_number,
          url: $pr_url
        },
        message: "CI checks timed out after \($timeout) seconds. PR created but not merged.",
        next_steps: ["Wait for CI to complete", "Manually merge when ready"]
      }'
    exit 1
  fi
fi

# Check PR merge status
MERGE_STATUS=$(gh pr view "$PR_NUMBER" --json mergeable,mergeStateStatus --jq '{mergeable: .mergeable, state: .mergeStateStatus}')
MERGEABLE=$(echo "$MERGE_STATUS" | jq -r '.mergeable')
MERGE_STATE=$(echo "$MERGE_STATUS" | jq -r '.state')

if [ "$MERGEABLE" != "MERGEABLE" ] || [ "$MERGE_STATE" != "CLEAN" ]; then
  jq -n \
    --arg action "not_mergeable" \
    --arg milestone "$MILESTONE_TITLE" \
    --argjson pr_number "$PR_NUMBER" \
    --arg pr_url "$PR_URL" \
    --arg mergeable "$MERGEABLE" \
    --arg state "$MERGE_STATE" \
    '{
      action: $action,
      milestone: $milestone,
      pr: {
        number: $pr_number,
        url: $pr_url,
        mergeable: $mergeable,
        merge_state: $state
      },
      message: "PR not in mergeable state: \($mergeable)/\($state)",
      next_steps: ["Resolve merge conflicts or CI failures", "Manually merge when ready"]
    }'
  exit 0
fi

# Merge the PR
echo "Merging PR #$PR_NUMBER..." >&2
MERGE_RESULT=$(gh pr merge "$PR_NUMBER" --squash --delete-branch 2>&1) && MERGE_SUCCESS=true || MERGE_SUCCESS=false

if [ "$MERGE_SUCCESS" = true ]; then
  jq -n \
    --arg action "merged" \
    --arg milestone "$MILESTONE_TITLE" \
    --argjson pr_number "$PR_NUMBER" \
    --arg pr_url "$PR_URL" \
    --argjson commits "$COMMITS_AHEAD" \
    '{
      action: $action,
      milestone: $milestone,
      pr: {
        number: $pr_number,
        url: $pr_url,
        merged: true
      },
      commits_promoted: $commits,
      message: "Successfully promoted dev to qa. \($commits) commits merged.",
      notifications: {
        success: "Milestone \($milestone) has been promoted to QA. PR #\($pr_number) merged.",
        next_steps: "QA validation can now begin. After sign-off, run /pr-to-main to release."
      }
    }'
else
  jq -n \
    --arg action "merge_failed" \
    --arg milestone "$MILESTONE_TITLE" \
    --argjson pr_number "$PR_NUMBER" \
    --arg pr_url "$PR_URL" \
    --arg error "$MERGE_RESULT" \
    '{
      action: $action,
      milestone: $milestone,
      pr: {
        number: $pr_number,
        url: $pr_url
      },
      message: "Failed to merge PR: \($error)",
      next_steps: ["Check merge requirements", "Manually merge when ready"]
    }'
  exit 1
fi
