#!/bin/bash
set -euo pipefail
# webhook-listener-setup.sh
# Setup wizard for the GitHub webhook listener
#
# This script helps configure and deploy the webhook listener service
# that receives GitHub PR events and triggers n8n workflows.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Show usage
usage() {
    cat <<EOF
Webhook Listener Setup

Usage: $0 [command] [options]

Commands:
    setup       Interactive setup wizard (default)
    start       Start the webhook listener
    stop        Stop the webhook listener
    status      Check service status
    logs        View logs
    tunnel      Start ngrok/smee tunnel for local development
    test        Send test webhook event

Options:
    --port PORT         Webhook listener port (default: 9000)
    --n8n-url URL       n8n webhook URL (default: http://n8n:5678/webhook/pr-review)
    --secret SECRET     GitHub webhook secret
    --help              Show this help

Examples:
    $0 setup                    # Run setup wizard
    $0 start                    # Start services
    $0 tunnel --port 9000       # Start ngrok tunnel
    $0 test                     # Send test event
EOF
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    local missing=()

    if ! command -v docker &>/dev/null; then
        missing+=("docker")
    fi

    if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null; then
        missing+=("docker-compose")
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        log_info "Please install the missing tools and try again"
        exit 1
    fi

    # Check if Docker is running
    if ! docker info &>/dev/null; then
        log_error "Docker daemon is not running"
        log_info "Please start Docker and try again"
        exit 1
    fi

    log_success "All prerequisites met"
}

# Interactive setup
setup_wizard() {
    echo ""
    echo "=========================================="
    echo "   Webhook Listener Setup Wizard"
    echo "=========================================="
    echo ""

    # Check if .env exists
    local env_file="$REPO_ROOT/deploy/webhook-listener/.env"

    if [ -f "$env_file" ]; then
        log_warn "Configuration file already exists: $env_file"
        read -p "Overwrite? [y/N] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            return 0
        fi
    fi

    # Collect configuration
    echo "Step 1: GitHub Webhook Secret"
    echo "Generate one with: openssl rand -hex 32"
    read -p "Enter webhook secret (or press Enter to generate): " webhook_secret
    if [ -z "$webhook_secret" ]; then
        webhook_secret=$(openssl rand -hex 32)
        log_info "Generated secret: $webhook_secret"
    fi

    echo ""
    echo "Step 2: Webhook Port"
    read -p "Listener port [9000]: " port
    port=${port:-9000}

    echo ""
    echo "Step 3: n8n Webhook URL"
    read -p "n8n webhook URL [http://n8n:5678/webhook/pr-review]: " n8n_url
    n8n_url=${n8n_url:-http://n8n:5678/webhook/pr-review}

    # Write .env file
    cat > "$env_file" <<EOF
# Webhook Listener Configuration
# Generated by webhook-listener-setup.sh on $(date)

# GitHub webhook secret (keep this secure!)
GITHUB_WEBHOOK_SECRET=$webhook_secret

# Listener configuration
WEBHOOK_PORT=$port

# n8n configuration
N8N_WEBHOOK_URL=$n8n_url
EOF

    log_success "Configuration saved to $env_file"

    echo ""
    echo "Step 4: GitHub Repository Setup"
    echo ""
    echo "Add this webhook to your GitHub repository:"
    echo "  Settings → Webhooks → Add webhook"
    echo ""
    echo "  Payload URL: http://YOUR_PUBLIC_URL:$port/webhook"
    echo "  Content type: application/json"
    echo "  Secret: $webhook_secret"
    echo "  Events: Pull requests"
    echo ""
    echo "For local development, use ngrok or smee.io:"
    echo "  $0 tunnel --port $port"
    echo ""

    read -p "Start services now? [Y/n] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        start_services
    fi
}

# Start services
start_services() {
    log_info "Starting webhook listener and n8n..."

    cd "$REPO_ROOT/deploy/webhook-listener"

    # Build and start
    docker compose up -d --build

    # Wait for health checks
    log_info "Waiting for services to be healthy..."
    sleep 5

    # Check status
    if docker compose ps | grep -q "healthy"; then
        log_success "Services started successfully"
        echo ""
        echo "Webhook listener: http://localhost:9000"
        echo "n8n:              http://localhost:5678"
        echo ""
        echo "View logs: $0 logs"
    else
        log_warn "Services may not be fully healthy yet"
        docker compose ps
    fi
}

# Stop services
stop_services() {
    log_info "Stopping services..."
    cd "$REPO_ROOT/deploy/webhook-listener"
    docker compose down
    log_success "Services stopped"
}

# Show status
show_status() {
    cd "$REPO_ROOT/deploy/webhook-listener"

    echo ""
    echo "=== Service Status ==="
    docker compose ps

    echo ""
    echo "=== Health Checks ==="

    # Check webhook listener
    if curl -sf http://localhost:9000/health >/dev/null 2>&1; then
        log_success "Webhook listener: healthy"
    else
        log_error "Webhook listener: not responding"
    fi

    # Check n8n
    if curl -sf http://localhost:5678/healthz >/dev/null 2>&1; then
        log_success "n8n: healthy"
    else
        log_error "n8n: not responding"
    fi
}

# Show logs
show_logs() {
    cd "$REPO_ROOT/deploy/webhook-listener"
    docker compose logs -f
}

# Start tunnel
start_tunnel() {
    local port=${1:-9000}

    if command -v ngrok &>/dev/null; then
        log_info "Starting ngrok tunnel on port $port..."
        ngrok http $port
    elif command -v smee &>/dev/null; then
        log_info "Starting smee client..."
        echo "Create a channel at https://smee.io and run:"
        echo "  smee -u YOUR_SMEE_URL -p $port -P /webhook"
    else
        log_error "No tunnel tool found"
        echo ""
        echo "Install one of:"
        echo "  - ngrok: brew install ngrok"
        echo "  - smee:  npm install -g smee-client"
        echo ""
        echo "Or use a free service:"
        echo "  - https://smee.io"
        echo "  - https://ngrok.com"
        exit 1
    fi
}

# Send test event
send_test() {
    local port=${1:-9000}

    log_info "Sending test webhook event..."

    local test_payload='{
        "action": "opened",
        "number": 999,
        "pull_request": {
            "number": 999,
            "title": "Test PR from webhook-listener-setup",
            "html_url": "https://github.com/test/repo/pull/999",
            "head": {"ref": "feature/test", "sha": "abc123"},
            "base": {"ref": "dev"}
        },
        "repository": {
            "full_name": "test/repo",
            "html_url": "https://github.com/test/repo"
        }
    }'

    local response
    response=$(curl -sf -X POST "http://localhost:$port/webhook" \
        -H "Content-Type: application/json" \
        -H "X-GitHub-Event: pull_request" \
        -d "$test_payload" 2>&1) || {
        log_error "Failed to send test event"
        echo "$response"
        exit 1
    }

    log_success "Test event sent"
    echo "Response: $response"
}

# Parse arguments
COMMAND="${1:-setup}"
shift || true

PORT=9000

while [[ $# -gt 0 ]]; do
    case "$1" in
        --port)
            PORT="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            shift
            ;;
    esac
done

# Main
check_prerequisites

case "$COMMAND" in
    setup)
        setup_wizard
        ;;
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    status)
        show_status
        ;;
    logs)
        show_logs
        ;;
    tunnel)
        start_tunnel "$PORT"
        ;;
    test)
        send_test "$PORT"
        ;;
    *)
        usage
        exit 1
        ;;
esac
