#!/usr/bin/env bash
set -euo pipefail

# Worker entrypoint: clone repo, create branch, run Claude Code on issue, push, create PR.
# Called by Proxmox worker-webhook with env vars:
#   GITHUB_TOKEN        — repo access
#   ANTHROPIC_API_KEY   — Claude API
#   ISSUE_NUMBER        — GitHub issue to work on
#   REPO                — owner/repo (default: jifflee/eagle-eye)
#   BRANCH_PREFIX       — branch prefix (default: fix)

REPO="${REPO:-jifflee/eagle-eye}"
ISSUE="${ISSUE_NUMBER:?ISSUE_NUMBER is required}"
BRANCH_PREFIX="${BRANCH_PREFIX:-fix}"

echo "=== Eagle Eye Worker ==="
echo "Issue:  #${ISSUE}"
echo "Repo:   ${REPO}"
echo "========================"

# --- Auth ---
echo "${GITHUB_TOKEN}" | gh auth login --with-token
git config --global user.name "eagle-eye-worker"
git config --global user.email "noreply@eagle-eye-worker"

# --- Clone & Branch ---
gh repo clone "${REPO}" /workspace/repo -- --depth=50
cd /workspace/repo

ISSUE_TITLE=$(gh issue view "${ISSUE}" --json title -q '.title' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | cut -c1-50)
BRANCH="${BRANCH_PREFIX}/issue-${ISSUE}-${ISSUE_TITLE}"
git checkout -b "${BRANCH}"

# --- Fetch issue context ---
ISSUE_BODY=$(gh issue view "${ISSUE}" --json title,body,labels -q '
  "Issue #\(.number): \(.title)\n\nLabels: \(.labels | map(.name) | join(", "))\n\n\(.body)"
')

# --- Run Claude Code ---
echo "Starting Claude Code on issue #${ISSUE}..."

claude --print --dangerously-skip-permissions \
  "You are working on issue #${ISSUE} in the ${REPO} repository.

Here is the issue:
${ISSUE_BODY}

Instructions:
1. Read the relevant source files to understand the codebase
2. Implement the fix or feature described in the issue
3. Run any available tests to verify your changes
4. Commit your changes with a message referencing the issue (Fixes #${ISSUE})

Do NOT push or create PRs — the entrypoint script handles that.
Keep changes minimal and focused on the issue."

# --- Push & PR ---
if git diff --quiet HEAD; then
  echo "No changes made. Exiting."
  exit 0
fi

git push origin "${BRANCH}"

PR_URL=$(gh pr create \
  --base main \
  --title "${BRANCH_PREFIX}: ${ISSUE_TITLE} (#${ISSUE})" \
  --body "$(cat <<EOF
## Summary
Automated fix for #${ISSUE}.

## Test plan
- [ ] Review changes
- [ ] Run backend tests
- [ ] Verify fix addresses acceptance criteria

Fixes #${ISSUE}

Generated by eagle-eye-worker container on docker-workers VM.
EOF
)")

echo "========================"
echo "PR created: ${PR_URL}"
echo "========================"
