#!/bin/bash
set -euo pipefail
# pr-orchestrate.sh
# Automated PR orchestration with check validation and auto-merge
#
# Usage:
#   ./scripts/pr-orchestrate.sh <PR_NUMBER> [OPTIONS]
#   ./scripts/pr-orchestrate.sh --on-create <PR_NUMBER>
#   ./scripts/pr-orchestrate.sh --on-update <PR_NUMBER>
#
# Options:
#   --on-create       Triggered when PR is created
#   --on-update       Triggered when PR is updated
#   --auto-merge      Auto-merge to dev if checks pass (default for dev branch)
#   --no-auto-merge   Disable auto-merge even for dev branch
#   --post-to-issue   Post failures to linked issue
#   --dry-run         Show what would be done without executing
#   --json            Output JSON format
#   --verbose         Show detailed output
#
# Exit Codes:
#   0 - PR processed successfully (merged or ready)
#   1 - PR needs fixes (validation failed)
#   2 - PR is pending (checks in progress)
#   3 - Error (invalid PR, API failure)
#
# Environment Variables:
#   PR_ORCHESTRATE_AUTO_MERGE  Set to "false" to disable auto-merge globally

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults
PR_NUMBER=""
EVENT_TYPE=""  # on-create, on-update, or empty (manual)
AUTO_MERGE=""  # auto, true, false (empty = auto-detect)
POST_TO_ISSUE=false
DRY_RUN=false
JSON_OUTPUT=false
VERBOSE=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --on-create)
      EVENT_TYPE="on-create"
      shift
      ;;
    --on-update)
      EVENT_TYPE="on-update"
      shift
      ;;
    --auto-merge)
      AUTO_MERGE="true"
      shift
      ;;
    --no-auto-merge)
      AUTO_MERGE="false"
      shift
      ;;
    --post-to-issue)
      POST_TO_ISSUE=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --json)
      JSON_OUTPUT=true
      shift
      ;;
    --verbose|-v)
      VERBOSE=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 <PR_NUMBER> [OPTIONS]"
      echo ""
      echo "Automated PR orchestration with check validation and auto-merge."
      echo ""
      echo "Options:"
      echo "  --on-create       Triggered when PR is created"
      echo "  --on-update       Triggered when PR is updated"
      echo "  --auto-merge      Auto-merge to dev if checks pass"
      echo "  --no-auto-merge   Disable auto-merge"
      echo "  --post-to-issue   Post failures to linked issue"
      echo "  --dry-run         Show what would be done"
      echo "  --json            Output JSON format"
      echo "  --verbose         Show detailed output"
      echo ""
      echo "Exit codes:"
      echo "  0 - Success (merged or ready)"
      echo "  1 - Needs fixes"
      echo "  2 - Pending"
      echo "  3 - Error"
      exit 0
      ;;
    *)
      if [[ -z "$PR_NUMBER" && "$1" =~ ^[0-9]+$ ]]; then
        PR_NUMBER="$1"
      else
        echo "Error: Unknown argument: $1" >&2
        exit 3
      fi
      shift
      ;;
  esac
done

# Validate arguments
if [[ -z "$PR_NUMBER" ]]; then
  echo "Error: PR number required" >&2
  exit 3
fi

# Logging helpers
log() {
  if ! $JSON_OUTPUT; then
    echo -e "$1"
  fi
}

log_verbose() {
  if $VERBOSE && ! $JSON_OUTPUT; then
    echo -e "${CYAN}[$(date '+%H:%M:%S')]${NC} $1"
  fi
}

log_step() {
  if ! $JSON_OUTPUT; then
    echo -e "${BLUE}→${NC} $1"
  fi
}

# Get PR base branch
get_pr_base_branch() {
  local pr_num="$1"
  gh pr view "$pr_num" --json baseRefName --jq '.baseRefName' 2>/dev/null || echo ""
}

# Extract linked issue from PR
get_linked_issue() {
  local pr_num="$1"
  local pr_body
  pr_body=$(gh pr view "$pr_num" --json body --jq '.body // ""' 2>/dev/null) || pr_body=""
  echo "$pr_body" | grep -oiE '(fixes|closes|resolves)\s*#[0-9]+' | head -1 | grep -oE '[0-9]+' || echo ""
}

# Post failure comment to linked issue
post_failure_to_issue() {
  local issue_num="$1"
  local pr_num="$2"
  local validation_result="$3"

  if [[ -z "$issue_num" ]]; then
    log_verbose "No linked issue to post to"
    return 0
  fi

  local failures
  failures=$(echo "$validation_result" | jq -r '.failures[] | "- **\(.name)**: \(.description)"')

  local remediations
  remediations=$(echo "$validation_result" | jq -r '.remediations[] | "- **\(.check)**: \(.suggestion)"')

  local comment_body
  comment_body=$(cat <<EOF
## PR Validation Failed

PR #$pr_num requires fixes before it can be merged.

### Failures
$failures

### How to Fix
$remediations

---
*Auto-generated by PR orchestration*
EOF
)

  if $DRY_RUN; then
    log "Would post to issue #$issue_num:"
    log "$comment_body"
    return 0
  fi

  log_verbose "Posting failure report to issue #$issue_num"
  gh issue comment "$issue_num" --body "$comment_body" 2>/dev/null || {
    log_verbose "Failed to post comment to issue #$issue_num"
    return 1
  }
}

# Post success comment to linked issue
post_success_to_issue() {
  local issue_num="$1"
  local pr_num="$2"
  local action="$3"  # "merged" or "ready"

  if [[ -z "$issue_num" ]]; then
    return 0
  fi

  local comment_body
  if [[ "$action" == "merged" ]]; then
    comment_body="PR #$pr_num has been automatically merged. Issue can now be closed."
  else
    comment_body="PR #$pr_num passed all validation checks and is ready for review/merge."
  fi

  if $DRY_RUN; then
    log "Would post to issue #$issue_num: $comment_body"
    return 0
  fi

  log_verbose "Posting success to issue #$issue_num"
  gh issue comment "$issue_num" --body "$comment_body" 2>/dev/null || true
}

# Perform auto-merge
perform_auto_merge() {
  local pr_num="$1"

  if $DRY_RUN; then
    log "Would auto-merge PR #$pr_num"
    return 0
  fi

  log_step "Auto-merging PR #$pr_num..."

  # Use worktree-safe merge if available
  if [[ -x "$SCRIPT_DIR/worktree-safe-merge.sh" ]]; then
    "$SCRIPT_DIR/worktree-safe-merge.sh" "$pr_num" --squash --delete-branch 2>&1 || {
      log_verbose "worktree-safe-merge failed, trying gh pr merge"
      gh pr merge "$pr_num" --squash --delete-branch 2>&1
    }
  else
    gh pr merge "$pr_num" --squash --delete-branch 2>&1
  fi
}

# Main orchestration logic
main() {
  log ""
  log "PR Orchestration: #$PR_NUMBER"
  log "==============================="
  [[ -n "$EVENT_TYPE" ]] && log "Event: $EVENT_TYPE"
  log ""

  # Step 1: Get PR info
  log_step "Fetching PR information..."
  local base_branch
  base_branch=$(get_pr_base_branch "$PR_NUMBER")

  if [[ -z "$base_branch" ]]; then
    if $JSON_OUTPUT; then
      echo "{\"pr_number\": $PR_NUMBER, \"status\": \"error\", \"summary\": \"Failed to fetch PR information\"}"
    else
      echo -e "${RED}Error: Could not fetch PR #$PR_NUMBER${NC}"
    fi
    exit 3
  fi

  local linked_issue
  linked_issue=$(get_linked_issue "$PR_NUMBER")
  log_verbose "Base branch: $base_branch, Linked issue: ${linked_issue:-none}"

  # Step 2: Determine auto-merge behavior
  # Auto-merge is enabled by default for dev branch only
  local should_auto_merge=false
  if [[ "$AUTO_MERGE" == "true" ]]; then
    should_auto_merge=true
  elif [[ "$AUTO_MERGE" == "false" ]]; then
    should_auto_merge=false
  elif [[ "${PR_ORCHESTRATE_AUTO_MERGE:-}" == "false" ]]; then
    should_auto_merge=false
  elif [[ "$base_branch" == "dev" ]]; then
    should_auto_merge=true
  fi

  log_verbose "Auto-merge enabled: $should_auto_merge"

  # Step 3: Run validation
  log_step "Running validation checks..."
  local validation_result
  validation_result=$("$SCRIPT_DIR/pr-validate.sh" "$PR_NUMBER" --json 2>/dev/null) || {
    if $JSON_OUTPUT; then
      echo "{\"pr_number\": $PR_NUMBER, \"status\": \"error\", \"summary\": \"Validation script failed\"}"
    else
      echo -e "${RED}Error: Validation failed${NC}"
    fi
    exit 3
  }

  local validation_status
  validation_status=$(echo "$validation_result" | jq -r '.status')
  local validation_summary
  validation_summary=$(echo "$validation_result" | jq -r '.summary')
  local checks_passed
  checks_passed=$(echo "$validation_result" | jq '.checks.passed')
  local checks_total
  checks_total=$(echo "$validation_result" | jq '.checks.total')

  log_verbose "Validation status: $validation_status"

  # Step 4: Handle based on validation result
  local final_status="$validation_status"
  local final_action="none"
  local merged=false

  case "$validation_status" in
    mergeable)
      log ""
      log -e "${GREEN}✓ All checks passed ($checks_passed/$checks_total)${NC}"

      if $should_auto_merge; then
        # Verify PR is still clean before merge
        local merge_state
        merge_state=$(gh pr view "$PR_NUMBER" --json mergeStateStatus --jq '.mergeStateStatus' 2>/dev/null) || merge_state="UNKNOWN"

        if [[ "$merge_state" == "CLEAN" ]]; then
          if perform_auto_merge "$PR_NUMBER"; then
            final_action="merged"
            merged=true
            log -e "${GREEN}✓ PR #$PR_NUMBER auto-merged to $base_branch${NC}"

            # Post success to issue
            if [[ -n "$linked_issue" ]]; then
              post_success_to_issue "$linked_issue" "$PR_NUMBER" "merged"
            fi
          else
            final_action="merge_failed"
            log -e "${RED}✗ Auto-merge failed${NC}"
          fi
        else
          log -e "${YELLOW}⏳ Merge state is $merge_state, skipping auto-merge${NC}"
          final_action="awaiting_clean_state"
        fi
      else
        final_action="ready"
        log "Auto-merge disabled, PR is ready for manual merge"

        # Post ready status to issue
        if [[ -n "$linked_issue" ]] && $POST_TO_ISSUE; then
          post_success_to_issue "$linked_issue" "$PR_NUMBER" "ready"
        fi
      fi
      ;;

    needs_fixes)
      log ""
      log -e "${RED}✗ Validation failed ($checks_passed/$checks_total checks passed)${NC}"
      final_action="needs_fixes"

      # Show failures
      if ! $JSON_OUTPUT; then
        log ""
        log "Failures:"
        echo "$validation_result" | jq -r '.failures[] | "  - \(.name): \(.description)"'
        log ""
        log "Remediations:"
        echo "$validation_result" | jq -r '.remediations[] | "  - \(.suggestion)"'
      fi

      # Post to linked issue if enabled
      if $POST_TO_ISSUE && [[ -n "$linked_issue" ]]; then
        post_failure_to_issue "$linked_issue" "$PR_NUMBER" "$validation_result"
        log ""
        log -e "${CYAN}Failure report posted to issue #$linked_issue${NC}"
      fi
      ;;

    pending)
      log ""
      log -e "${YELLOW}⏳ Checks still in progress${NC}"
      final_action="pending"
      ;;

    *)
      log ""
      log -e "${RED}? Unknown validation status: $validation_status${NC}"
      final_action="error"
      ;;
  esac

  # Build final output
  if $JSON_OUTPUT; then
    jq -n \
      --arg pr_number "$PR_NUMBER" \
      --arg status "$final_status" \
      --arg action "$final_action" \
      --argjson merged "$merged" \
      --arg base_branch "$base_branch" \
      --arg linked_issue "${linked_issue:-null}" \
      --argjson validation "$validation_result" \
      --arg event_type "${EVENT_TYPE:-manual}" \
      --argjson auto_merge "$should_auto_merge" \
      --argjson dry_run "$DRY_RUN" \
      '{
        pr_number: ($pr_number | tonumber),
        status: $status,
        action: $action,
        merged: $merged,
        base_branch: $base_branch,
        linked_issue: (if $linked_issue == "null" or $linked_issue == "" then null else ($linked_issue | tonumber) end),
        validation: $validation,
        event_type: $event_type,
        auto_merge_enabled: $auto_merge,
        dry_run: $dry_run
      }'
  else
    log ""
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log "Result: $final_action"
    [[ -n "$linked_issue" ]] && log "Linked Issue: #$linked_issue"
    [[ "$merged" == "true" ]] && log "Merged: Yes"
    log ""
  fi

  # Exit with appropriate code
  case "$final_status" in
    mergeable) exit 0 ;;
    needs_fixes) exit 1 ;;
    pending) exit 2 ;;
    *) exit 3 ;;
  esac
}

main
